# Inherits from your CPU-only base image
FROM ghcr.io/robotics-avv/docker_files/jazzy_base:latest

# NVIDIA GPU settings for hardware acceleration
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility
